# ruff.toml

# Menyesuaikan dengan standar Black (line length 88)
line-length = 88
exclude = ["app/db/migrations"]

# Aturan yang akan dicek
[lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort (mengurutkan import)
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
]
ignore = [
    "E501", # Mengabaikan peringatan Line too long (biarkan formatter yang menangani)
    "B008", # Mengabaikan function call in default argument (sering dipakai di FastAPI Depends)
]

[format]
quote-style = "double"
indent-style = "space"
