"""create merchant catalog item with pgvector

Revision ID: 9aef02516199
Revises: b60a730a89e8
Create Date: 2026-07-18 23:24:12.316556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '9aef02516199'
down_revision: Union[str, None] = 'b60a730a89e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_catalog_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('source_type', postgresql.ENUM('photo', 'manual', name='catalog_source_type_enum'), nullable=False),
    sa.Column('confidence', postgresql.ENUM('high', 'low', name='catalog_confidence_enum'), server_default='high', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_catalog_items_merchant_id'), 'merchant_catalog_items', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_catalog_items_merchant_id'), table_name='merchant_catalog_items')
    op.drop_table('merchant_catalog_items')
    
    source_type_enum = postgresql.ENUM('photo', 'manual', name='catalog_source_type_enum')
    source_type_enum.drop(op.get_bind())
    
    confidence_enum = postgresql.ENUM('high', 'low', name='catalog_confidence_enum')
    confidence_enum.drop(op.get_bind())
    # ### end Alembic commands ###
