"""create_credit_score_logs

Revision ID: 9e88a38c21ba
Revises: 
Create Date: 2026-07-20 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e88a38c21ba'
down_revision = '5c2c477600a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_score_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'period', name='uq_merchant_credit_score_period')
    )
    op.create_index(op.f('ix_credit_score_logs_merchant_id'), 'credit_score_logs', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_score_logs_merchant_id'), table_name='credit_score_logs')
    op.drop_table('credit_score_logs')
    # ### end Alembic commands ###
