"""expand merchant profile for catalog ingestion

Revision ID: b60a730a89e8
Revises: 8a6d7558209f
Create Date: 2026-07-18 23:12:16.730030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b60a730a89e8'
down_revision: Union[str, None] = '8a6d7558209f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    merchant_status_enum = postgresql.ENUM('pending', 'active', 'suspended', name='merchant_status_enum')
    merchant_status_enum.create(op.get_bind())
    
    op.add_column('merchants', sa.Column('is_redemption_partner', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('merchants', sa.Column('baseline_rating', sa.Numeric(precision=2, scale=1), server_default='4.0', nullable=False))
    op.add_column('merchants', sa.Column('review_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('merchants', sa.Column('baseline_inventory', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('merchants', sa.Column('qris_image_url', sa.Text(), nullable=True))
    op.add_column('merchants', sa.Column('status', postgresql.ENUM('pending', 'active', 'suspended', name='merchant_status_enum'), server_default='pending', nullable=False))
    op.add_column('merchants', sa.Column('daily_ingest_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('merchants', sa.Column('ingest_count_reset_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'ingest_count_reset_at')
    op.drop_column('merchants', 'daily_ingest_count')
    op.drop_column('merchants', 'status')
    op.drop_column('merchants', 'qris_image_url')
    op.drop_column('merchants', 'baseline_inventory')
    op.drop_column('merchants', 'review_count')
    op.drop_column('merchants', 'baseline_rating')
    op.drop_column('merchants', 'is_redemption_partner')
    merchant_status_enum = postgresql.ENUM('pending', 'active', 'suspended', name='merchant_status_enum')
    merchant_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
