"""create transactions stamps promos

Revision ID: b7d2e821b0f4
Revises: 5c2c477600a9
Create Date: 2026-07-19 21:10:14.300123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7d2e821b0f4'
down_revision: Union[str, None] = '5c2c477600a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ENUMS
    op.execute("CREATE TYPE discount_type_enum AS ENUM ('percentage', 'fixed_amount')")
    op.execute("CREATE TYPE redemption_status_enum AS ENUM ('pending', 'redeemed', 'expired')")

    # TRANSACTIONS
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('tourist_user_id', sa.UUID(), nullable=True),
    sa.Column('nominal_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('item_reference', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linked_itinerary_id', sa.UUID(), nullable=True),
    sa.Column('client_reference_id', sa.String(length=64), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_itinerary_id'], ['itineraries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tourist_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'client_reference_id', name='uq_merchant_client_ref')
    )
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_transactions_tourist_user_id'), 'transactions', ['tourist_user_id'], unique=False)

    # STAMPS
    op.create_table('stamps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_stamps_user_id'), 'stamps', ['user_id'], unique=False)

    # PROMOS
    op.create_table('promos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('discount_type', postgresql.ENUM('percentage', 'fixed_amount', name='discount_type_enum', create_type=False), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stamp_required_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promos_merchant_id'), 'promos', ['merchant_id'], unique=False)

    # PROMO REDEMPTIONS
    op.create_table('promo_redemptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('promo_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('redemption_code', sa.String(length=8), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'redeemed', 'expired', name='redemption_status_enum', create_type=False), server_default='pending', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promo_id'], ['promos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_redemptions_redemption_code'), 'promo_redemptions', ['redemption_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promo_redemptions_redemption_code'), table_name='promo_redemptions')
    op.drop_table('promo_redemptions')
    op.drop_index(op.f('ix_promos_merchant_id'), table_name='promos')
    op.drop_table('promos')
    op.drop_index(op.f('ix_stamps_user_id'), table_name='stamps')
    op.drop_table('stamps')
    op.drop_index(op.f('ix_transactions_tourist_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_table('transactions')
    
    op.execute("DROP TYPE redemption_status_enum")
    op.execute("DROP TYPE discount_type_enum")
    # ### end Alembic commands ###
