"""create_itineraries_table

Revision ID: d1a0eb9033e1
Revises: 7cbd372229f3
Create Date: 2026-07-19 02:39:09.599310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1a0eb9033e1'
down_revision: Union[str, None] = '7cbd372229f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('itineraries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('raw_query', sa.String(), nullable=False),
    sa.Column('parsed_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('waypoints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('route_geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'active', 'completed', name='itinerary_status_enum'), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('itineraries')

    # ### end Alembic commands ###
